### ISSUE TITLE
最新のmacOSでは正しくmigemoが実行出来ない

### ISSUE THREAD

**Issue by y-vectorfield** [rhysd/migemo-search.vim#3]
最新のmacOSではユーザーがHomebrewを利用して追加したアプリケーションは`/opt/homebrew`配下に格納されることになりました．その変更に伴い旧来のディレクトリパスからはmigemoの辞書ファイルが読み出せず，エラーとなってしまいます．

**Comment by rhysd** [comment]
Closed by #4.
